app:
  name: dnsx
  model: debug # debug / test / release
  port: 53

mysql:
  dns: dnsx:password@tcp(127.0.0.1:3306)/dnsx?charset=utf8&parseTime=True&loc=Local
  conn_max_lifetime: 2000
  max_open_conn: 100
  max_idle_conn: 5
  log_model: true

api:
  addr: :8081

log:
  log_path: ./logs/
  log_file_name: dnsx
  log_level: debug
  encoder: json
  max_size: 1024
  max_backups: 3
  max_age: 7
  request_log: true
  stdout: true

pprof:
  open: false
  addr: :8001
